# Generated by Django 3.2.16 on 2023-08-11 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_images'),
    ]

    operations = [
        migrations.RenameField('Post', 'images', 'image')
    ]
